# Self-Hosted Github Action Runners on AWS via Cirun.io
# Reference: https://docs.cirun.io/reference/yaml
runners:
  - name: "cirun-runner"
    # Cloud Provider: GCP
    cloud: "gcp"
    instance_type: "t2a-standard-2"
    machine_image: "ubuntu-2204-jammy-arm64-v20240208"
    preemptible: false
    # Add this label in the "runs-on" param in .github/workflows/<workflow-name>.yml
    # So that this runner is created for running the workflow
    labels:
      - "cirun-gcp-runner"
